#!/usr/bin/env bash
#Copyright (c) 2021 Tschallacka

# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
if [ $# -eq 0 ]
  then
    echo "Please provide a version to switch to. Available versions are"
    ls -a /usr/lib/php/ | grep ^[0-9]\.[0-9]$ | tr '\n' ' '
    echo
    echo "usage: switch_php [version number]"
    exit
fi
PHP_VERSION=`php -r "echo substr(phpversion(),0,3);"`
sudo a2dismod "php$PHP_VERSION" && sudo a2enmod "php$1"
echo "Restarting apache"
sudo systemctl restart apache2
sudo update-alternatives --set php "/usr/bin/php$1"
